site_name: 2020_5CI_Team3
nav:
    - 'Index': 'index.md'
    - 'Project Model Canvas': 'project_model_canvas.md'
    - 'Business Model Canvas': 'business_model_canvas.md'
    - 'Project Charter': 'proj_charter.md'
    - 'Software Requirements Specification': 'software_requirements_specification.md'
    - 'Software Management Plan': 'software_management_plan.md'
    - 'Release Plan': 'release_plan.md'
    - 'Iteration Plan': 'iteration_plan.md'
    - 'Memo of Understanding': 'memo_of_understanding.md'
    - 'Project Success Criteria': 'project_success_criteria.md'
    - 'Architecture and Design': 'architecture_and_design.md'
    - 'Coding Standards': 'coding_standards.md'
    - 'Test plan': 'test_plan.md'
    - 'User guide': 'user_guide.md'
    - 'Test Case Specification': 'test_case_specification.md'
    - 'System Documentation': 'system_documentation.md'

    - 'Project Model Canvas': 'pdf/project_model_canvas.pdf'
    - 'Business Model Canvas': 'pdf/business_model_canvas.pdf'
    - 'Project Charter': 'pdf/proj_charter.pdf'
    - 'Software Requirements Specification': 'pdf/software_requirements_specification.pdf'
    - 'Software Management Plan': 'pdf/software_management_plan.pdf'
    - 'Release Plan': 'pdf/release_plan.pdf'
    - 'Iteration Plan': 'pdf/iteration_plan.pdf'
    - 'Memo of Understanding': 'pdf/memo_of_understanding.pdf'
    - 'Project Success Criteria': 'pdf/project_success_criteria.pdf'
    - 'Architecture and Design': 'pdf/architecture_and_design.pdf'
    - 'Coding Standards': 'pdf/coding_standards.pdf'
    - 'Test plan': 'pdf/test_plan.pdf'
    - 'User guide': 'pdf/user_guide.pdf'
    - 'Test Case Specification': 'pdf/test_case_specification.pdf'
    - 'System Documentation': 'pdf/system_documentation.pdf'

theme:
    name: readthedocs

use_directory_urls: true
