site_name: 2020_5CI_Team3
nav:
    - 'Index': 'index.md'
    - 'Project Model Canvas': 'project_model_canvas.md'
    - 'Business Model Canvas': 'business_model_canvas.md'
    - 'Project Charter': 'proj_charter.md'
    - 'Software Requirements Specification': 'software_requirements_specification.md'
    - 'Software Management Plan': 'software_management_plan.md'
    - 'Release Plan': 'release_plan.md'
    - 'Iteration Plan': ''
    - 'Memo of Understanding': ''
    - 'Project Success Criteria': ''
    - 'Architecture and Design': 'architecture_and_design.md'
    - 'Coding Standards': 'coding_standards.md'
    - 'Test plan': 'test_plan.md'
    - 'User guide': 'user_guide.md'
    - 'Test Case Specification': 'test_case_specification.md'
    - 'System Documentation': 'system_documentation.md'

theme:
    name: readthedocs

use_directory_urls: true
