site_name: 2020_5CI_Team3
nav:
    - 'Index': 'index.md'
    - 'Business Model Canvas': 'business_model_canvas.md'
    - 'Project Charter': 'proj_charter.md'
    - 'Project Model Canvas': 'project_model_canvas.md'
    - 'Software Management Plan': 'software_management_plan.md'
    - 'Software Requirements Specification': 'software_requirements_specification.md'
    - 'System documentation': 'system_documentation.md'
    - 'Release plan': 'release_plan.md'


theme:
    name: readthedocs

use_directory_urls: true
